# This file is part of HDL Code Checker.
#
# HDL Code Checker is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# HDL Code Checker is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with HDL Code Checker.  If not, see <http://www.gnu.org/licenses/>.
---
dist: precise
language: python
python:
  - "2.7"

env:
  matrix:
    - BUILDER=msim
    - BUILDER=ghdl
    # - BUILDER=xvhdl

before_install:
  - if [ "$BUILDER" == "msim" ]; then
      sudo apt-get update -qq;
      sudo apt-get install -qq libgd2-xpm ia32-libs ia32-libs-multiarch;
    fi

before_script:
  - "mkdir -p ~/cache"
  - if [ "${BUILDER}" == "msim" ]  ; then "./.ci/setup_msim.sh"; fi
  - if [ "${BUILDER}" == "ghdl" ]  ; then "./.ci/setup_ghdl.sh"; fi
  - if [ "${BUILDER}" == "xvhdl" ] ; then "./.ci/setup_xvhdl.sh"; fi
  # Add all builders to the path; vunit should find the right one
  - export PATH=~/builders/msim/modelsim_ase/bin:$PATH
  - export PATH=~/builders/ghdl/bin/:$PATH
  - export PATH=~/builders/xvhdl/bin/:$PATH
# command to install dependencies
install:
  - pip install vunit_hdl
# command to run tests
script: "./run_tests.sh"
cache:
  pip: true
  directories:
    - ~/cache/
